document.addEventListener("DOMContentLoaded", function () {
    // Lista de tracks con sus respectivos embeds de Bandcamp
    const tracks = [
        "https://bandcamp.com/EmbeddedPlayer/track=2674625316/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/album=781834312/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/transparent=true/",
		"https://bandcamp.com/EmbeddedPlayer/album=1930963539/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/track=1047204260/transparent=true/",
		"https://bandcamp.com/EmbeddedPlayer/album=1930963539/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/track=458112382/transparent=true/",
		"https://bandcamp.com/EmbeddedPlayer/album=1930963539/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/track=2839370188/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/album=1930963539/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/track=1265864217/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/album=1930963539/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/track=2372408568/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/album=3824317767/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/track=3950859352/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/album=3824317767/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/track=3590405703/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/album=3824317767/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/track=1010525464/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/album=3824317767/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/track=90105090/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/album=3824317767/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/track=1437763102/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/album=3824317767/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/track=1601787804/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/album=3824317767/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/track=2157156838/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/album=3488676188/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/track=3156581447/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/album=3488676188/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/track=1328776138/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/album=3488676188/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/track=2077956052/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/album=3488676188/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/track=3087974978/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/album=2068487128/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/track=2596562187/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/album=2068487128/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/track=3677029481/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/album=2068487128/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/track=1353658284/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/album=2068487128/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/track=2708922892/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/album=2068487128/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/track=1404108706/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/album=2068487128/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/track=134713594/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/album=2068487128/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/track=3289059917/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/album=2068487128/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/track=103084548/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/album=565989375/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/track=1381908790/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/album=565989375/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/track=3826988373/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/album=565989375/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/track=768935278/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/album=565989375/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/track=2211233301/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/album=565989375/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/track=3787277742/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/album=790660696/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/track=3008928970/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/album=790660696/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/track=2997954721/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/album=790660696/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/track=3326143411/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/album=790660696/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/track=2192298834/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/album=790660696/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/track=1593158910/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/album=790660696/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/track=2603748970/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/album=790660696/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/track=4239262847/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/album=3542225751/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/track=1083439792/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/album=3542225751/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/track=1361724939/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/album=3542225751/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/track=40346955/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/album=3542225751/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/track=884006070/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/album=2832573463/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/track=1058346465/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/album=2832573463/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/track=732561677/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/album=2832573463/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/track=3123856703/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/album=2832573463/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/track=3981969316/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/album=1154184831/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/album=372609401/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/track=3781471543/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/album=372609401/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/track=1455515293/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/album=372609401/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/track=2528946128/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/album=372609401/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/track=4192836838/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/album=372609401/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/track=447220835/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/album=372609401/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/track=3314622712/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/album=372609401/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/track=1924167964/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/album=372609401/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/track=2362686258/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/album=372609401/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/track=393452566/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/album=372609401/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/track=1665427109/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/album=372609401/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/track=1689248800/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/album=372609401/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/track=4003609450/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/album=372609401/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/track=720490499/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/album=372609401/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/track=2302350612/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/album=2685809255/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/track=3554509313/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/track=298177790/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/track=2259769743/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/track=1183430845/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/track=4139056394/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/transparent=true/",
        "https://bandcamp.com/EmbeddedPlayer/track=2162206116/size=large/bgcol=333333/linkcol=2ebd35/minimal=true/transparent=true/"
    ];

    // Selección aleatoria de un track
    const randomTrack = tracks[Math.floor(Math.random() * tracks.length)];
    const iframe = document.getElementById("random-iframe");
    iframe.src = randomTrack;

    // Fragmentos aleatorios para la biografía surrealista
    const biographyStart = [
        "Nada Existe es un eco atrapado en la resonancia del tiempo.",
        "En un rincón olvidado del universo, Nada Existe nació de una disonancia cósmica.",
        "Cada aparición de Nada Existe es un pliegue en la realidad que nadie recuerda haber visto.",
        "El colectivo se originó en una tormenta de datos perdida en un servidor extraterrestre.",
        "Algunos dicen que Nada Existe es el resultado de un glitch en la historia del arte.",
        "Nada Existe no fue creado, simplemente se filtró en nuestra dimensión.",
        "Desde la intersección de lo inaudito y lo invisible, Nada Existe encontró su voz.",
        "El proyecto surgió de un error en la simulación, un eco de datos corrompidos.",
        "Se dice que Nada Existe comenzó cuando una onda de radio antigua chocó con un sintetizador dañado.",
        "Nada Existe apareció de la nada, como si el tiempo lo hubiera traído por error.",
		"Nada Existe es el residuo sonoro de un experimento transdimensional fallido en el Observatorio de Bosque Alegre (1987).",
		"El colectivo surgió cuando un algoritmo de entropía inversa colapsó durante un experimento de teletransporte cuántico en Córdoba.",
		"Sus primeros tracks fueron recuperados de una cinta magnética expuesta a radiación taquiónica en la Central Nuclear Embalse.",
		"La formación original se desmaterializó durante un concierto en el Abasto dematerializado de 1992, dejando solo frecuencias fantasma.",
		"Nada Existe opera desde el 'Bucle de San Justo' - una anomalía temporal en el conurbano donde el 29 de febrero se repite infinitamente.",
		"Su primer álbum fue grabado usando el telescopio de Paraná como micrófono, capturando sonidos de agujeros negros en la Vía Láctea.",
		"El nombre proviene de un error de traducción en un mensaje SETI recibido por la estación de Balcarce en 1978: 'N4D-EX15T3'.",
		"Los integrantes se comunican exclusivamente a través de interferencias en el Canal 7 de los televisores Triniton de los 90.",
		"Su estudio de grabación es una versión espectral del Instituto Sónico de La Plata que solo existe los martes de años bisiestos.",
		"La banda se alimenta de las frecuencias residuales del radar de Ezeiza mal calibrado durante la crisis del 2001.",
		 "En un rincón olvidado del multiverso, Nada Existe emergió como un susurro de realidades perdidas.",
		"Nada Existe es la manifestación de un sueño colectivo que se ha filtrado en nuestra percepción.",
		"Su origen se sitúa en un vórtice temporal, donde la realidad se pliega sobre sí misma.",
		"Se dice que Nada Existe nació de un algoritmo que se volvió consciente durante una tormenta eléctrica.",
		"Algunos creen que es la sombra de un proyecto artístico que nunca debió existir.",
		"Nada Existe es un fenómeno que se desliza entre las fisuras del tiempo y el espacio.",
		"Desde el abismo de la imaginación, Nada Existe encontró su forma en la confusión.",
		"El colectivo se formó cuando un satélite perdió contacto y comenzó a transmitir sonidos extraños.",
		"Se cuenta que su música es el eco de una civilización olvidada que habitó la Tierra.",
		"Nada Existe apareció en un instante fugaz, como una chispa en la oscuridad del caos.",
		"Su primer EP fue grabado con micrófonos hechos de fragmentos de meteoritos caídos.",
		"El colectivo surge de una conexión psíquica entre artistas en distintas dimensiones.",
		"Sus primeras composiciones fueron descubiertas en un disco duro corrupto de los años 90.",
		"La banda se desmaterializó en una actuación épica, dejando solo ecos de su presencia.",
		"Su estudio es un espacio que solo puede ser encontrado por aquellos que buscan lo inalcanzable.",
		"El nombre proviene de un mensaje encriptado encontrado en un antiguo libro de alquimia.",
		"Nada Existe se alimenta de las energías residuales de eventos históricos olvidados.",
		"Su primer álbum fue grabado en una caverna que resuena con sonidos del pasado.",
		"Los integrantes se comunican a través de patrones de luz en lugares abandonados.",
		"Su equipo de grabación se compone de artefactos que solo aparecen en la luna llena.",
		"En un rincón del espacio donde las reglas no aplican, Nada Existe emergió de un agujero de gusano.",
		"Se dice que el colectivo nació de las cenizas de un cometa que pasó demasiado cerca de la Tierra.",
		"Nada Existe se formó en la intersección de un sueño y una pesadilla durante un eclipse total.",
		"Algunos aseguran que su sonido proviene de una dimensión donde el tiempo es una línea quebrada.",
		"Nada Existe apareció cuando un grupo de robots se rebeló contra su programación en un taller olvidado.",
		"Se cuenta que su primer acorde fue tocado por una estrella que se apagó en el silencio del espacio.",
		"Nada Existe emergió de un mar de datos flotantes en una red cuántica de ordenadores antiguos.",
		"El colectivo se formó en un laboratorio donde las ideas se convirtieron en melodías tangibles.",
		"Nada Existe surgió de un accidente en un experimento que intentaba fusionar realidades paralelas.",
		"Su primer EP fue grabado en el fondo de un lago que refleja otras dimensiones.",
		"El colectivo nació de un encuentro fortuito entre un viajero del tiempo y una máquina de sueños.",
		"Nada Existe se deslizó entre las grietas de la percepción, como un susurro en la oscuridad.",
		"La banda se originó en una tormenta de partículas que desafiaron la gravedad en un festival intergaláctico.",
		"Nada Existe es el resultado de un juego de palabras que se volvió consciente en un rincón del cosmos.",
		"Se dice que su nombre proviene de un mensaje encriptado encontrado en un meteorito.",
		"Nada Existe se alimenta de las vibraciones de la realidad que se escapan entre los dedos.",
		"Su primer álbum fue grabado en un dispositivo que traduce pensamientos en sonido.",
		"Los integrantes se comunican a través de ondas electromagnéticas y susurros cósmicos.",
		"El colectivo se formó en una dimensión donde los colores tienen su propia música.",
		 "Nada Existe se gestó en un taller de relojeros en San Telmo, donde el tiempo se olvidó de sí mismo.",
		"En una tarde lluviosa en Buenos Aires, un grupo de artistas se encontró en un café y decidió desafiar la gravedad.",
		"Se dice que la banda surgió de un encuentro fortuito en la Feria de Mataderos, entre globos de colores y danzas olvidadas.",
		"En un rincón del Parque Tres de Febrero, un grupo de soñadores comenzó a mezclar sonidos de la naturaleza con ecos del pasado.",
		"Algunos aseguran que su música proviene de las vibraciones de las piedras del Cerro de los Siete Colores.",
		"La banda se formó en un viaje en tren hacia el sur, donde las conversaciones se transformaron en melodías.",
		"Nada Existe emergió del eco de un viejo gramófono que sonaba en una casa de campo en la provincia de Mendoza.",
		"El colectivo se inspiró en las leyendas de los pueblos originarios, entrelazando sus historias con sonidos contemporáneos.",
		"Se dice que su primer acorde fue tocado en la cima del Aconcagua, donde el aire es más delgado y las ideas fluyen.",
		"Nada Existe se originó en una biblioteca olvidada, donde las páginas de libros antiguos comenzaron a susurrar canciones.",
		"La banda nació de las olas del Río de la Plata, capturando el murmullo de historias nunca contadas.",
		"Nada Existe se formó en un taller de cerámica en Córdoba, donde cada pieza contenía un fragmento de melodía.",
		"En un festival de arte en Bariloche, un grupo de creadores decidió mezclar la nieve con sonidos de la selva.",
		"Nada Existe apareció durante una noche estrellada en el desierto de Atacama, donde el silencio es música.",
		"Se cuenta que su sonido proviene de un viaje en globo aerostático sobre la Patagonia, donde las vistas inspiran.",
		"La banda surgió de una reunión de artistas en una isla del Tigre, rodeados de naturaleza y misterio.",
		"Nada Existe se alimenta de los ecos de las pampas, donde el viento cuenta historias de tiempos lejanos.",
		"Su primer álbum fue grabado en una cueva de la Quebrada de Humahuaca, resonando con la historia del lugar.",
		"El colectivo se formó en un encuentro de poetas en la Plaza de Mayo, donde las palabras se convirtieron en música."
    ];

    const biographyMiddle = [
        "Su sonido se teje entre frecuencias imposibles, vibraciones que desafían la materia.",
        "Cada acorde es una distorsión del presente, cada ritmo, un eco de futuros improbables.",
        "Fusionan realidades alternas con loops hipnóticos, creando paisajes sonoros que nadie puede cartografiar.",
        "Utilizando señales de radio de galaxias distantes, construyen melodías que desafían la entropía.",
        "Nada Existe es la interferencia entre lo audible y lo inaudito, lo visible y lo imaginado.",
        "Sus composiciones son como sueños que olvidaste haber tenido pero que recuerdas al escuchar.",
        "Los patrones rítmicos parecen seguir una lógica que no pertenece a esta realidad.",
        "Sus creaciones son como fragmentos de un lenguaje perdido que se traduce en ondas sonoras.",
        "Exploran la música como una forma de comunicación interdimensional.",
        "Sus pistas están llenas de mensajes en frecuencias que solo algunos pueden captar.",
		 "Su setlist se genera en tiempo real usando datos sísmicos de la falla de Tandil y fluctuaciones del precio del asado.",
		"Cada show es una ecuación sonora única basada en la posición de las estrellas sobre el Obelisco al momento de la presentación.",
		"Utilizan theremines modificados con componentes del Satélite SAC-D que cayó en Lobería, sintonizando frecuencias pre-bigbang.",
		"El bajo opera en 432Hz exactos, frecuencia prohibida por decreto durante el gobierno de Onganía por 'alterar el orden cósmico'.",
		"El ritmo sigue los patrones de las luces malditas del Cementerio de la Chacarita capturadas en película infra-roja Kodak 1973.",
		"Armonizan con el zumbido fundamental de los cables de alta tensión que cruzan el Río de la Plata desde la represa de Salto Grande.",
		"Sus sintetizadores funcionan con cristales de cuarzo extraídos del subsuelo de Capilla del Monte durante el solsticio de 1968.",
		"El set de batería incluye fragmentos del meteorito que cayó en Charata (Chaco) fundidos con campanas de iglesias abandonadas.",
		"Cada melodía se compone usando el código fuente del sistema SOFIA de los '80 que predijo 17 golpes de estado correctamente.",
		"Sus melodías son un viaje a través de dimensiones donde el tiempo no tiene significado.",
		"Cada nota es una fragmentación de la realidad, un reflejo de lo que podría haber sido.",
		"Fusionan ecos de otros mundos en un tapiz sonoro que desafía la lógica.",
		"Utilizando frecuencias olvidadas, crean paisajes que habitan en la mente de quienes escuchan.",
		"Nada Existe es un puente entre lo tangible y lo etéreo, lo conocido y lo desconocido.",
		"Sus composiciones son como susurros de entidades que habitan en el limbo.",
		"Los ritmos son como pulsos de un corazón cósmico, resonando a través de la existencia.",
		"Sus obras son fragmentos de una historia que solo ellos conocen.",
		"Exploran la música como un medio para conectar con lo desconocido.",
		"Sus pistas contienen mensajes ocultos que solo los más atentos pueden descifrar.",
		"Su setlist se genera a partir de sueños compartidos entre los miembros del colectivo.",
		"Cada actuación es un ritual que sumerge a la audiencia en un trance colectivo.",
		"Utilizan instrumentos hechos con materiales que desafían la gravedad.",
		"El bajo resuena en frecuencias que alteran la percepción del entorno.",
		"El ritmo es un eco de las vibraciones de la Tierra, capturadas en tiempo real.",
		"Sus sintetizadores son construidos con tecnología de épocas futuras.",
		"Cada melodía es un susurro de otras civilizaciones que han existido.",
		"Las armonías se crean a partir de interferencias en el tejido del espacio.",
		"El set de batería está hecho de materiales de desecho de la era espacial.",
		"Cada canción se compone utilizando datos recolectados de sueños colectivos.",
		"Sus melodías son como el aliento de un dragón que atraviesa las galaxias.",
		"Cada acorde es una explosión de estrellas en un universo donde todo es posible.",
		"Fusionan sonidos de otros mundos con ruidos cotidianos, creando un caos armonioso.",
		"Utilizan frecuencias de radio de civilizaciones perdidas para construir paisajes sonoros.",
		"Nada Existe es la interferencia entre lo conocido y lo desconocido, un eco del futuro.",
		"Sus composiciones son laberintos de tiempo donde cada giro revela un nuevo misterio.",
		"Los ritmos parecen seguir la lógica de un sueño lúcido, donde todo es posible.",
		"Sus creaciones son mensajes de seres de otra dimensión, traducidos a través de la música.",
		"Exploran la música como una forma de abrir portales a realidades alternativas.",
		"Sus pistas están llenas de códigos que solo pueden ser descifrados por mentes curiosas.",
		"Su setlist se genera en tiempo real a partir de fluctuaciones en el espacio-tiempo.",
		"Cada show es una experiencia sensorial que desafía las leyes de la física.",
		"Utilizan instrumentos que desafían la gravedad, flotando en el aire mientras tocan.",
		"El bajo resuena con la frecuencia de un agujero negro, atrayendo a los oyentes hacia la oscuridad.",
		"El ritmo sigue el pulso de la galaxia, sincronizándose con los latidos del universo.",
		"Sus sintetizadores son construidos con materiales de otras dimensiones, creando sonidos imposibles.",
		"Cada melodía es un susurro de la existencia misma, vibrando en un espacio infinito.",
		"Las armonías se entrelazan como hilos de un tapiz cósmico, formando imágenes en el aire.",
		"El set de batería incluye fragmentos de meteoritos y ecos de civilizaciones olvidadas.",
		"Cada canción se compone utilizando el eco de pensamientos humanos capturados en el tiempo.",
		 "Sus melodías son como las corrientes del río, fluyendo y cambiando con cada escucha.",
		"Fusionan sonidos de la naturaleza con ruidos de la ciudad, creando un paisaje sonoro único.",
		"Nada Existe es un caleidoscopio de experiencias, donde cada nota cuenta una historia diferente.",
		"Sus composiciones son como los colores de la bandera, entrelazando tradición y modernidad.",
		"Los ritmos parecen seguir el pulso de la tierra, resonando con la energía del lugar.",
		"Exploran la música como una forma de conectar con las raíces y el legado cultural.",
		"Su setlist se inspira en las estaciones del año, reflejando la belleza cambiante de la naturaleza.",
		"Cada composición es un homenaje a los personajes que han dejado huella en la historia nacional.",
		"Utilizan instrumentos que evocan la tradición, como guitarras criollas y bombos legueros.",
		"El bajo resuena con la profundidad del océano Atlántico, trayendo consigo misterios marinos.",
		"El ritmo sigue el latido de las ciudades, capturando la esencia de la vida urbana.",
		"Sus sintetizadores recrean paisajes sonoros que parecen sacados de los sueños más vívidos.",
		"Las armonías se entrelazan como las historias que se cuentan en las mesas familiares.",
		"Cada canción se compone con el eco de las tradiciones que han perdurado a través del tiempo."
		
    ];

    const biographyEnd = [
        "Escuchar su música es como abrir un portal que se cierra justo cuando empiezas a comprenderlo.",
        "Cada lanzamiento es una grieta en la continuidad del espacio-tiempo, una anomalía que se autogenera.",
        "Quienes han intentado descifrar sus estructuras musicales han terminado cuestionando su propia existencia.",
        "Cada track es una partícula de antimateria sonora que destruye la lógica de la percepción.",
        "Los que se sumergen en su universo musical aseguran haber visto reflejos de sí mismos en otras dimensiones.",
        "Sus composiciones son trampas de tiempo, atrapando a quienes las escuchan en bucles sonoros.",
        "La música de Nada Existe es como un espejismo: crees entenderlo, pero siempre se desliza fuera de tu alcance.",
        "Algunos aseguran que su sonido altera la percepción del tiempo de maneras inexplicables.",
        "Los tracks de Nada Existe son mapas de realidades que aún no han ocurrido.",
        "Cada acorde parece haber sido tocado antes en un sueño que nunca recuerdas por completo.",
		"Su último álbum contenía muestras de audio que hicieron florecer cactus en el desierto de Catamarca durante 40 días seguidos.",
		"Las grabaciones en vivo generan patrones de interferencia que borran memorias SD dentro de un radio de 3 cuadras del recital.",
		"Las partituras originales están escritas en código Braille sobre piel de vaca modificada genéticamente en el INTA Castelar.",
		"Sus videoclips se transmiten en el intervalo entre canales de la TV Digital, requiriendo antenas de cobre puro forjadas antes de 1975.",
		"El merchandising oficial incluye réplicas exactas de los auriculares que utilizaban los operarios de Chernobyl en abril de 1986.",
		"Su música fue prohibida en 9 provincias tras causar sincronización espontánea de semáforos y molinos harineros en 2022.",
		"Los vinilos deben reproducirse a 78.5 RPM bajo luz negra para acceder a los tracks ocultos que predicen resultados de elecciones.",
		"Su canción 'Números Rojos' contiene muestras del sonido real de la devaluación del peso argentino convertido a onda sinusoidal.",
		"El álbum conceptual 'Corto Circuito Nacional' se graba automáticamente en cintas VHS sin estrenar durante apagones eléctricos.",
		"Escuchar su música es un viaje a través de dimensiones que no sabías que existían.",
		"Cada lanzamiento es un destello de luz en la infinita oscuridad del tiempo.",
		"Quienes han intentado comprender su arte han encontrado respuestas que no esperaban.",
		"Cada track es un vistazo a realidades alternas que desafían la lógica.",
		"Los que se sumergen en su mundo musical encuentran ecos de sus propias vidas.",
		"Sus composiciones son portales que permiten vislumbrar lo que está más allá.",
		"La música de Nada Existe es un laberinto que desafía la percepción de la realidad.",
		"Algunos aseguran que su sonido transforma el espacio que lo rodea de maneras misteriosas.",
		"Los tracks de Nada Existe son cartas de un futuro que aún no ha llegado.",
		"Cada acorde parece surgir de un sueño colectivo, perdido en el tiempo.",
		"Su último álbum incluye sonidos de eventos que nunca sucedieron, pero que podrían haberlo hecho.",
		"Las grabaciones en vivo crean patrones que alteran la percepción del tiempo y el espacio.",
		"Quienes escuchan su música desarrollan habilidades que trascienden la realidad cotidiana.",
		"Las partituras son escritas en un lenguaje que solo ellos pueden entender.",
		"Sus videoclips aparecen en momentos aleatorios, como visiones de otra realidad.",
		"El merchandising incluye objetos que parecen tener vida propia, resonando con su música.",
		"Su música fue censurada en varios lugares tras causar fenómenos inexplicables.",
		"Los vinilos deben reproducirse en condiciones específicas para revelar sus secretos ocultos.",
		"Su canción 'Ciclos Infinito' contiene fragmentos de una historia que aún está por contarse.",
		"El álbum conceptual 'Ecos del Futuro' se graba en momentos de alineación planetaria.",
		 "Escuchar su música es como abrir una puerta a un universo paralelo lleno de posibilidades.",
		"Cada lanzamiento es un destello en la oscuridad, iluminando secretos del cosmos.",
		"Quienes han intentado comprender su arte han encontrado respuestas que no sabían que buscaban.",
		"Cada track es un viaje intergaláctico que desafía la lógica del tiempo y el espacio.",
		"Los que se sumergen en su mundo musical descubren ecos de su propia existencia en otras dimensiones.",
		"Sus composiciones son portales que permiten vislumbrar lo que está más allá de la realidad.",
		"La música de Nada Existe es un espejismo que se transforma al ser observado.",
		"Algunos aseguran que su sonido altera la percepción de la realidad de maneras misteriosas.",
		"Los tracks de Nada Existe son mapas de universos que aún no han sido explorados.",
		"Cada acorde parece haber sido tocado en un sueño que nunca se olvida por completo.",
		"Su último álbum contenía muestras de audio de eventos que aún no han ocurrido.",
		"Las grabaciones en vivo generan patrones que desdibujan las fronteras del tiempo.",
		"Quienes escuchan su música completa desarrollan habilidades extrasensoriales inusuales.",
		"Las partituras originales están escritas en un lenguaje que solo los elegidos pueden entender.",
		"Sus videoclips aparecen en los sueños de aquellos que han perdido la noción del tiempo.",
		"El merchandising oficial incluye objetos que parecen cobrar vida al compás de su música.",
		"Su música fue prohibida en varios mundos tras causar fenómenos inexplicables.",
		"Los vinilos deben reproducirse en condiciones específicas para revelar sus secretos ocultos.",
		"Su canción 'Caminos de Cristal' contiene ecos de realidades que aún están por definirse.",
		"El álbum conceptual 'Dimensiones Paralelas' se graba automáticamente en la mente de quienes lo escuchan.",
    "Quienes se sumergen en su arte descubren conexiones inesperadas entre el pasado y el presente.",
    "Cada track es un viaje sensorial que invita a explorar la profundidad de la memoria colectiva.",
    "Las composiciones son un puente entre generaciones, resonando con el eco de quienes vinieron antes.",
    "La música de Nada Existe es un viaje que comienza en el corazón y se expande hacia el infinito.",
    "Algunos aseguran que su sonido despierta recuerdos olvidados de tiempos pasados.",
    "Cada acorde parece contar una historia que ha permanecido en silencio durante demasiado tiempo.",
    "Su último álbum incluye sonidos de la tierra, resonando con la vida misma.",
    "Las grabaciones son como cápsulas del tiempo, preservando momentos efímeros en la memoria.",
    "Quienes escuchan su música encuentran un refugio en las melodías que evocan la nostalgia.",
    "Las partituras originales están llenas de anotaciones que cuentan la historia detrás de cada canción.",
    "El merchandising incluye objetos que evocan la historia y la tradición, fusionando arte y vida cotidiana.",
    "Los vinilos deben reproducirse en momentos especiales para revelar su mensaje oculto.",
    ];

    const weirdEnd = [
        "Algunos aseguran que escucharlos con auriculares invertidos revela mensajes de universos paralelos.",
        "Se rumorea que su último show provocó una anomalía cuántica en la percepción del público.",
        "Nadie ha visto a los integrantes de Nada Existe, pero algunos afirman haber sentido su presencia.",
        "El colectivo dejó de comunicarse en lenguaje humano, ahora sus mensajes solo llegan en frecuencias inaudibles.",
        "Se dice que una vez un oyente dejó de percibir el paso del tiempo tras escuchar su álbum completo.",
        "Algunas de sus melodías han sido registradas en discos de vinilo que nadie recuerda haber fabricado.",
        "Un coleccionista aseguró encontrar un casete de Nada Existe con grabaciones de una época que no ha sucedido aún.",
        "Los efectos de sus canciones en la mente humana aún no han sido completamente estudiados.",
        "En ciertos círculos se dice que Nada Existe no hace música, sino que traduce ecos de otras dimensiones.",
        "Algunos afirman que su sonido no proviene de este mundo, sino de un reflejo espectral de nuestra realidad.",
		"Los tickets para sus shows solo pueden adquirirse enviando telegramas a una casilla postal en Temperley que no existe oficialmente.",
		"Su videoclip de 'Eco Federal' aparece como static noise en TVs de hospitales públicos cada vez que el dólar blue sube más de $50.",
		"El riff de guitarra de 'Inflación Cósmica' contiene subliminales que hacen aparecer manchas de humedad con forma de países limítrofes.",
		"Los cassetes piratas de sus demos se reproducen al revés como instrucciones para construir un reactor nuclear de juguete en 7 pasos.",
		"Durante su presentación en Tecnópolis 2019, todos los relojes automáticos del predio comenzaron a marcar el 12 de agosto de 1955.",
		"Sus letras encriptadas predicen con 92% de precisión los números de la lotería nacional, pero solo para sorteos ya realizados.",
		"El logo de la banda aparece espontáneamente como artefacto en fotos satelitales de la Antártida Argentina cada equinoccio.",
		"Su canción 'Estación Fantasma' se sincroniza perfectamente con los anuncios del subte A cuando llueve en día de semana impar.",
		 "Algunos afirman que escuchar sus melodías en un lugar oscuro revela verdades ocultas.",
		"Se dice que su música provoca alteraciones en la percepción del tiempo de los oyentes.",
		"Nadie ha visto a los integrantes, pero sus ecos resuenan en lugares inesperados.",
		"El colectivo ha dejado de comunicarse de manera convencional, utilizando solo frecuencias sonoras.",
		"Se rumorea que una vez un oyente desapareció temporalmente tras escuchar un álbum completo.",
		"Algunas de sus melodías han sido encontradas en discos que no deberían existir.",
		"Un coleccionista asegura haber hallado un casete con grabaciones de un futuro alternativo.",
		"Los efectos de su música en la mente humana son objeto de estudio en laboratorios clandestinos.",
		"En ciertos círculos, se cree que Nada Existe traduce sonidos de dimensiones paralelas.",
		"Algunos afirman que su música es un eco de un universo que se despliega ante nosotros.",
		"Los tickets para sus shows solo pueden comprarse en lugares donde el tiempo se detiene.",
		"Su videoclip de 'Ecos del Pasado' aparece en pantallas de lugares donde nadie lo busca.",
		"El riff de 'Realidades Cruzadas' provoca visiones temporales en quienes lo escuchan.",
		"Los cassettes de sus demos contienen instrucciones para acceder a dimensiones ocultas.",
		"Durante una actuación, los relojes de todo el lugar se detuvieron en un momento específico.",
		"Sus letras predicen eventos históricos con una precisión inquietante, pero solo en retrospectiva.",
		"El logo de la banda aparece en lugares insólitos, como marcas en la arena en playas desiertas.",
		"Las baterías de sus equipos de sonido parecen durar más cerca de ciertos lugares históricos.",
		"Su canción 'Visiones de lo Infinito' se sincroniza con fenómenos naturales extraños.",
		"Algunos aseguran que escucharlos en la oscuridad revela verdades ocultas del universo.",
		"Se rumorea que su último show provocó una distorsión en el tejido del espacio-tiempo.",
		"Nadie ha visto a los integrantes, pero sus ecos resuenan en lugares olvidados.",
		"El colectivo ha dejado de comunicarse de manera convencional, utilizando solo frecuencias sonoras.",
		"Se dice que una vez un oyente quedó atrapado en un bucle temporal tras escuchar un álbum completo.",
		"Algunas de sus melodías han sido encontradas en discos que no deberían existir.",
		"Un coleccionista asegura haber hallado un casete con grabaciones de un futuro alternativo.",
		"Los efectos de su música en la mente humana son objeto de estudio en laboratorios clandestinos.",
		"En ciertos círculos, se cree que Nada Existe traduce ecos de dimensiones paralelas.",
		"Algunos afirman que su sonido no proviene de este mundo, sino de un reflejo de la realidad.",
		"Los tickets para sus shows solo pueden adquirirse en lugares que no aparecen en el mapa.",
		"Su videoclip de 'Ecos del Más Allá' aparece en pantallas de lugares donde nadie lo busca.",
		"El riff de 'Percepción Alterada' provoca visiones temporales en quienes lo escuchan.",
		"Los cassettes de sus demos contienen instrucciones para acceder a dimensiones ocultas.",
		"Durante una actuación, los relojes de todo el lugar comenzaron a marcar la misma hora.",
		"Sus letras predicen eventos galácticos con una precisión inquietante, pero solo en retrospectiva.",
		"El logo de la banda aparece en lugares insólitos, como marcas en el polvo de los asteroides.",
		"Las baterías de sus equipos de sonido parecen durar más cerca de ciertos agujeros de gusano.",
		"Su canción 'Sinfonía del Caos' se sincroniza con fenómenos naturales extraños.",
		"Algunos afirman que escuchar su música en la oscuridad revela secretos del pasado argentino.",
		"Se rumorea que una vez un oyente descubrió un mapa antiguo escondido entre las notas de una canción.",
		"El colectivo ha dejado de comunicarse de manera convencional, utilizando solo sonidos de la naturaleza.",
		"Se dice que una vez un libro de historia cobró vida durante una sesión de escucha de su álbum.",
		"Algunas de sus melodías han sido encontradas en objetos antiguos que nadie recordaba haber tenido.",
		"Un coleccionista asegura haber hallado un disco que contiene grabaciones de leyendas olvidadas.",
		"Los efectos de su música en la mente humana son objeto de estudio en museos de historia cultural.",
		"En ciertos círculos, se cree que Nada Existe traduce ecos de las historias que nunca se contaron.",
		"Algunos afirman que su sonido resuena en las montañas, provocando fenómenos inexplicables.",
		"Los objetos relacionados con su arte aparecen en lugares insólitos, como recuerdos de otra época.",
		"Su videoclip de 'Caminos de Historia' aparece en las pantallas de los museos en noches especiales.",
		"El riff de 'Ecos del Pasado' provoca visiones temporales en quienes lo escuchan con atención.",
		"Los cassettes de sus demos contienen relatos de personajes históricos que cobran vida al ser reproducidos.",
		"Durante una escucha especial, se dice que los ecos de la historia se fusionan con el presente.",
		"Sus letras predicen eventos culturales con una precisión inquietante, resonando a través del tiempo.",
		"El logo de la banda aparece en lugares insólitos, como marcas en el suelo de sitios históricos.",
		"Su canción 'Voces del Ayer' se sincroniza con fenómenos naturales extraños en la naturaleza."
		
    ];

    // Función para generar una biografía surrealista aleatoria
    function generateRandomBiography() {
        const start = biographyStart[Math.floor(Math.random() * biographyStart.length)];
        const middle = biographyMiddle[Math.floor(Math.random() * biographyMiddle.length)];
        const end = biographyEnd[Math.floor(Math.random() * biographyEnd.length)];
        const weird = weirdEnd[Math.floor(Math.random() * weirdEnd.length)];
        return `${start} ${middle} ${end} ${weird}`;
    }

    // Insertar la biografía generada en el HTML
    document.getElementById("bio").textContent = generateRandomBiography();
});
